jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run tests
      run: ./gradlew check test jacocoTestReport --stacktrace
    - continue-on-error: true
      name: Send test results to CodeCov
      run: bash <(curl -s https://codecov.io/bash)
name: Test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
